name: Fetch Claude Code Docs

on:
  schedule:
    # Daily at 00:00 LA time (07:00 UTC during daylight time, 08:00 UTC during standard time)
    # Using 07:00 UTC for PDT (Pacific Daylight Time)
    - cron: "0 7 * * *"
  workflow_dispatch: # Allow manual trigger

jobs:
  fetch-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
      id-token: write
    env:
      AWS_REGION: us-west-2

    steps:
      - name: Generate GitHub App token
        id: app-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}

      - name: Fetch Claude Code docs
        run: ./fetchccdocs.sh --format md

      - name: Check for meaningful changes
        id: changes
        run: |
          # Exclude metadata-only changes
          git add .
          if git diff --cached --name-only | grep -v -E '(\.metadata|claude-code-manifest)\.json$' | head -1; then
            echo "changes=true" >> $GITHUB_OUTPUT
            echo "Found meaningful documentation changes"
          else
            echo "changes=false" >> $GITHUB_OUTPUT
            echo "Only metadata changes detected, skipping commit"
            git reset HEAD .
          fi

      - name: Analyze changes for PR
        if: steps.changes.outputs.changes == 'true'
        id: analyze
        run: |
          # Get list of changed files
          CHANGED_FILES=$(git diff --cached --name-only | grep -v -E '(\.metadata|claude-code-manifest)\.json$' | sort)
          echo "changed_files<<EOF" >> $GITHUB_OUTPUT
          echo "$CHANGED_FILES" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

          # Get summary stats
          FILES_COUNT=$(echo "$CHANGED_FILES" | wc -l)
          echo "files_count=$FILES_COUNT" >> $GITHUB_OUTPUT

          # Get timestamp
          FETCH_TIME=$(date -u +"%Y-%m-%d %H:%M:%S UTC")
          echo "fetch_time=$FETCH_TIME" >> $GITHUB_OUTPUT

      - name: Commit and create pull request
        if: steps.changes.outputs.changes == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ steps.app-token.outputs.token }}
          author: "claude-yolo[bot] <claude-yolo@lroole.com>"
          committer: "claude-yolo[bot] <claude-yolo@lroole.com>"
          commit-message: |
            docs: update Claude Code documentation

            Updated ${{ steps.analyze.outputs.files_count }} files from docs.anthropic.com
            Fetched: ${{ steps.analyze.outputs.fetch_time }}
          title: "docs: update Claude Code documentation (${{ steps.analyze.outputs.files_count }} files)"
          body: |
            ## Documentation Update

            Automated update fetched from docs.anthropic.com on **${{ steps.analyze.outputs.fetch_time }}**.

            ### Changed Files (${{ steps.analyze.outputs.files_count }})
            ```
            ${{ steps.analyze.outputs.changed_files }}
            ```

            ### Details
            - Source: docs.anthropic.com  
            - Workflow: Fetch Claude Code Docs
            - Trigger: ${{ github.event_name == 'schedule' && 'Scheduled (daily)' || 'Manual' }}

            This PR was automatically generated by the **Fetch Claude Code Docs** workflow.
          branch: docs/auto-update-${{ github.run_id }}
          delete-branch: true
